image: "node:12.0"

before_script:
  - apt-get update -qy
  - apt-get install -y yarn default-jdk
  - yarn global add gulp-cli

cache:
  key: ${CI_PROJECT_NAME} - ${CI_COMMIT_REF_SLUG}
  paths:
    - yarn.lock
    - node_modules/

test-job:
  stage: test
  script:
    - yarn
    - yarn test